# Generated by Django 4.2.30 on 2026-08-03 20:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('run_type', models.CharField(choices=[('DEBATE', 'Multi-Agent Debate'), ('REWRITE', 'Section Rewrite')], max_length=20)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='ACTIVE', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Blueprint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('QUEUED', 'Queued'), ('GENERATING', 'Generating'), ('PARTIALLY_GENERATED', 'Partially Generated'), ('READY', 'Ready'), ('EDITING', 'Editing'), ('EXPORTING', 'Exporting'), ('ARCHIVED', 'Archived'), ('FAILED', 'Failed'), ('DELETED', 'Deleted')], default='DRAFT', max_length=20)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('task_type', models.CharField(choices=[('GENERATE', 'Generate Blueprint'), ('REGENERATE', 'Regenerate Section')], max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('STARTED', 'Started'), ('SUCCESS', 'Success'), ('FAILURE', 'Failure')], default='PENDING', max_length=20)),
                ('current_node', models.CharField(blank=True, max_length=100)),
                ('error_log', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('blueprint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='blueprints.blueprint')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('MARKET', 'Market Analysis'), ('PRODUCT', 'Product Specification'), ('TECH_STACK', 'Technical Architecture'), ('BUSINESS', 'Business Model')], max_length=20)),
                ('sort_order', models.IntegerField(default=0)),
                ('blueprint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='blueprints.blueprint')),
            ],
            options={
                'ordering': ['sort_order'],
                'unique_together': {('blueprint', 'category')},
            },
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_number', models.IntegerField(default=1)),
                ('content_markdown', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versions', to='blueprints.agentrun')),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versions', to='blueprints.job')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='blueprints.section')),
            ],
            options={
                'ordering': ['-version_number'],
            },
        ),
        migrations.AddField(
            model_name='job',
            name='target_section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='blueprints.section'),
        ),
        migrations.CreateModel(
            name='Idea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ideas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Export',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('format', models.CharField(choices=[('MARKDOWN', 'Markdown'), ('PDF', 'PDF')], max_length=10)),
                ('storage_path', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('blueprint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exports', to='blueprints.blueprint')),
            ],
        ),
        migrations.AddField(
            model_name='blueprint',
            name='idea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blueprints', to='blueprints.idea'),
        ),
        migrations.AddField(
            model_name='blueprint',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blueprints', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='agentrun',
            name='blueprint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_runs', to='blueprints.blueprint'),
        ),
        migrations.AddField(
            model_name='agentrun',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_runs', to='blueprints.job'),
        ),
        migrations.CreateModel(
            name='AgentMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('agent_name', models.CharField(max_length=100)),
                ('message_type', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='blueprints.agentrun')),
            ],
        ),
    ]
