# Generated by Django 4.2.30 on 2026-08-03 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blueprints', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version',
            name='version_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
