# Generated by Django 4.2.30 on 2026-08-04 09:20

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blueprints', '0002_alter_version_version_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='DecisionLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('node_origin', models.CharField(max_length=50)),
                ('decision_key', models.CharField(max_length=100)),
                ('choice_value', models.TextField()),
                ('rationale', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('blueprint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='blueprints.blueprint')),
                ('created_by_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decisions', to='blueprints.version')),
                ('supersedes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='superseded_by', to='blueprints.decisionlog')),
            ],
        ),
    ]
