# Generated by Django 4.2.30 on 2026-08-04 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blueprints', '0003_decisionlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='decisionlog',
            name='priority',
            field=models.CharField(default='P1', max_length=10),
        ),
    ]
