# Generated by Django 4.2.30 on 2026-08-04 10:03

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blueprints', '0004_decisionlog_priority'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenerationEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=50)),
                ('details', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('blueprint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generation_events', to='blueprints.blueprint')),
            ],
        ),
    ]
