from abc import ABC, abstractmethod
from typing import Any, Dict, Generator, Optional, Type
from pydantic import BaseModel

class LLMService(ABC):
    """Abstract base class establishing the contract for LLM provider adapters."""

    @abstractmethod
    def generate(
        self,
        prompt: str,
        system_instruction: Optional[str] = None,
        options: Optional[Dict[str, Any]] = None
    ) -> str:
        """Generate a complete text response for a given prompt."""
        pass

    @abstractmethod
    def generate_stream(
        self,
        prompt: str,
        system_instruction: Optional[str] = None,
        options: Optional[Dict[str, Any]] = None
    ) -> Generator[str, None, None]:
        """Yield response text chunks sequentially as they are generated by the model."""
        pass

    @abstractmethod
    def generate_structured(
        self,
        prompt: str,
        output_schema: Type[BaseModel],
        system_instruction: Optional[str] = None
    ) -> BaseModel:
        """Generate response text forced to match the target Pydantic schema and return parsed instance."""
        pass

    @abstractmethod
    def count_tokens(self, text: str) -> int:
        """Count the number of tokens in the input text."""
        pass
