# Generated by Django 4.2.30 on 2026-08-04 09:20

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blueprints', '0003_decisionlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='DecisionDependency',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('parent_key', models.CharField(max_length=100)),
                ('child_key', models.CharField(max_length=100)),
                ('blueprint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decision_dependencies', to='blueprints.blueprint')),
            ],
            options={
                'unique_together': {('blueprint', 'parent_key', 'child_key')},
            },
        ),
    ]
